global:
  resolve_timeout: 5m
route:
  receiver: 'local-webhook'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
receivers:
  - name: 'local-webhook'
    webhook_configs:
      - url: 'http://backend:5000/api/alerts'
        send_resolved: true
